server:
  port: 8092

logging:
  file:
    path: src/main/resources/log
  level:
    root: off

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibbernate:
        dialect: org.hibernate.dialect.H2Dialect